"""Give a failing API-drift probe a durable artefact a human will actually meet.

**The workflow's own comments used to promise a notification that did not
exist.** "so a foreign API changing under us is something we are told rather than
something a curator discovers", and "the failure notification names which
contract moved" — the only route that existed was GitHub's default Actions email
for scheduled runs, which goes to *whoever last edited the cron file*, is silently
absent for anyone whose Actions notifications are off, and breaks the moment
somebody else touches the file. Nothing anywhere recorded that this was the route.

So the weekly museum probe could sit red for months while the product went on
being built against `artic-api-findings.md` as though it were re-verified, and the
drift-detection value would be silently zero.

**This is the replacement: an issue in the backlog the operator already reads.**
It survives an unread inbox, it does not depend on who touched the file last, and
it lands where the remedial work is tracked — reconciling the `*-api-findings.md`
document the probe was measuring against.

**One open issue per contract, and repeat failures comment rather than pile up.**
A weekly failure must not open a new issue every Monday. The title is stable per
contract, which is what makes the dedup possible, and each repeat adds a comment —
so the issue also records how long the contract has been moving, which is the one
thing a pile of duplicates would have told you and a silent no-op would not.

**Recovery is not automated, deliberately.** A probe going green again does not
mean the finding is discharged: the remedy is to reconcile the findings document
against what the API now returns, and only a human knows whether that happened.
Auto-closing on the next green run would retire the issue at exactly the moment
the evidence stopped being visible. The operator closes it, having done the work.

Usage: report_drift_failure.py <contract-name> <run-url>
Requires `gh` on PATH and a token with `issues: write`.
"""

import json
import subprocess
import sys

#: Applied to every issue this script opens, so the dedup search is a label query
#: rather than a title match against the whole backlog. A human filing a related
#: item by hand will not carry it, which is correct — this label means "opened by
#: the drift workflow, and the dedup key of one contract".
LABEL = "api-drift"


def _gh(*args: str) -> str:
    """Run `gh` and return stdout. Kept behind one seam so tests need no network."""
    return subprocess.run(["gh", *args], check=True, capture_output=True, text=True).stdout


def title_for(contract: str) -> str:
    """The stable dedup key. Same contract, same title, forever."""
    return f"api-drift: {contract} no longer matches what we recorded"


def choose(open_issues: list[dict], contract: str) -> int | None:
    """The number of the issue to comment on, or None to open a new one.

    Matched on the exact title rather than fuzzily: the title is generated by
    `title_for`, so anything that does not match it character-for-character is a
    different contract or a human's own issue, and commenting on someone else's
    item is worse than opening one too many.
    """
    wanted = title_for(contract)
    for issue in open_issues:
        if issue.get("title") == wanted:
            return issue["number"]
    return None


def body_for(contract: str, run_url: str) -> str:
    return (
        f"The scheduled API-drift probe for **{contract}** failed.\n\n"
        f"Failing run: {run_url}\n\n"
        "These probes are the durable form of the `*-api-findings.md` documents: each one "
        "re-verifies a measurement the product was written against. A failure here does not mean "
        "our code is wrong — the fakes in the default suite cover correctness.\n\n"
        "**Read the run first, because two different faults land here.** A failed *assertion* "
        "means a fact we built on has moved: compare it against what the API returns now and "
        "reconcile the findings document that recorded the original measurement. A failure from "
        "`assert_tests_ran.py` instead means the job verified nothing — an expired secret, a "
        "failed binary install — and the contract may be perfectly fine. The two send you to "
        "opposite places, and only the run says which one this is.\n\n"
        "Close this issue when you have done that work. It will not close itself: a green run "
        "proves the probe passed, not that anyone reconciled anything.\n\n"
        f"Repeat failures comment here rather than opening another issue, so the comment history "
        f"is how long `{contract}` has been failing."
    )


def main(contract: str, run_url: str, gh=_gh) -> int:
    # The label has to exist before either call below can use it, and nothing
    # creates it: `gh issue create --label api-drift` on a repository that has
    # never had one exits non-zero, so the very first real drift failure would
    # raise here instead of filing — the alerting path failing at exactly the
    # moment it was needed, and leaving no trace but a red workflow.
    #
    # `--force` is what makes this idempotent: without it the second run fails
    # because the label already exists, which is the same defect wearing the
    # opposite sign.
    gh("label", "create", LABEL, "--description", "Opened by the API-drift workflow", "--color", "B60205", "--force")

    found = json.loads(gh("issue", "list", "--state", "open", "--label", LABEL, "--limit", "100", "--json", "number,title"))
    existing = choose(found, contract)

    if existing is None:
        gh("issue", "create", "--title", title_for(contract), "--body", body_for(contract, run_url), "--label", LABEL)
        print(f"opened a new issue for {contract}")
    else:
        gh("issue", "comment", str(existing), "--body", f"Still failing, as of {run_url}")
        print(f"commented on #{existing} — {contract} was already reported")
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(__doc__)
        raise SystemExit(2)
    raise SystemExit(main(sys.argv[1], sys.argv[2]))
